server.port=${PORT:8080}

# Nouvelle URL avec domaine public
spring.datasource.url=jdbc:mysql://mysql-production-abfd.up.railway.app:3306/railway
spring.datasource.username=root
spring.datasource.password=laOHnsqMKceuNpRVesTjgeTEXtwcyViC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
