server.port=${PORT:8080}

# Nouvelle URL avec domaine public
spring.datasource.url=jdbc:mysql://mysql-1fa201e2-aribaymane61-6445.e.aivencloud.com:24713/ecocropsbd2?useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WHZjZLScaRtu6MGBqJW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
